const hour = document.getElementById('hour')
const min = document.getElementById('min')
const sec = document.getElementById('sec')
const mil = document.getElementById('mil')
const daylight = document.getElementById('daylight')
